{% set name = "google-generativeai" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google-gemini/generative-ai-python/archive/{{ version }}.tar.gz
  sha256: d44aa77865edc0d2a47e9c07106d2c9be72d3ff3a65340c5187f8d5c05745971

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - google-ai-generativelanguage =0.6.9
    - google-api-core
    - google-api-python-client
    - google-auth >=2.15.0
    - protobuf
    - pydantic
    - tqdm
    - typing-extensions

test:
  imports:
    - google
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/generative-ai-python
  summary: The Gemini API Python SDK enables developers to use Google's state-of-the-art generative AI models to build AI-powered features and applications.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
